function setup() {
    // Setup code goes here.
    // This function runs once.
    // The default canvas size, which is implied here, is 100 × 100 in pixels.
    // The 1-pixel gray border around the box is generated by style.css.
}

function draw() {
    rect(10, 10, 20, 20);
    rect(66, 10, 20, 20);
    rect(10, 66, 20, 20);
    rect(66, 66, 20, 20);
}
